### ISSUE TITLE
http-formatters - socket not available

### ISSUE THREAD

**Issue by FrizzaUK** [elastic/ecs-logging-nodejs#17]
I have an instance where socket is not available from the request, therefore the following test fails within the http-formatters.js:

`ecs.url.full = (socket.encrypted ? 'https://' : 'http://') + headers.host + url`

Can this be updated to test for the existence of socket?

`ecs.url.full = (socket && socket.encrypted ? 'https://' : 'http://') + headers.host + url`

**Comment by davisarchibald** [comment]
I can confirm this is happening for me as well. I'm using Fastify and their built in Pino logging and get this same error. I'd be happy to put together a PR with this change if there isn't something underlying that requires socket be there.

**Comment by Noteofman** [comment]
Can confirm this is happening for me as well.

**Comment by trentm** [comment]
Thanks all. Sorry for the delay (I took over maint of this repo fairly recently).

@davisarchibald  Note that I wasn't able to reproduce this using a naive fastify example like this:

```js
% cat fastify-example.js
const helpers = require('@elastic/ecs-helpers')
const fastify = require('fastify')({ logger: false })

fastify.get('/', async (request, reply) => {
  const rec = {}
  helpers.formatHttpRequest(rec, request)
  console.log('rec:', rec)
  return { hello: 'world' }
})

fastify.listen(3000)
```

If you or anyone has the stacktrace from a crash, or a repro handy, I would be much obliged.

**Comment by davisarchibald** [comment]
@trentm let me double check my implementation and see if I can get you what you need. I would say I've since learned a fair amount about `pino` and `fastify` and could have been an instance where I wasn't passing in the request in the correct way.

**Comment by davisarchibald** [comment]
@trentm curious what version of `fastify` you are on in your testing? Looks like they added a `socket` getter in version 3.6.0 so that its at the top level: https://github.com/fastify/fastify/pull/2594/files#diff-2871801a54601791d9e1004f04b2df5d7adc881560285ff3fa6bee7bf9697857R139 . I just updated our version to the latest and no longer see the issue.

**Comment by trentm** [comment]
Ah, that'll be it. I had just tested with the latest fastify as of today.  Trying with fastify@3.5.0 (and without the `socket &&` fix):

```
% node fastify-example.js | pino-pretty
[1612823103034] INFO (28873 on pink.local): Server listening at http://127.0.0.1:3000
[1612823104784] INFO (28873 on pink.local): incoming request
    reqId: 1
    req: {
      "method": "GET",
      "url": "/",
      "hostname": "localhost:3000",
      "remoteAddress": "127.0.0.1",
      "remotePort": 63308
    }
[1612823104786] ERROR (28873 on pink.local): Cannot read property 'encrypted' of undefined
    reqId: 1
    req: {
      "method": "GET",
      "url": "/",
      "hostname": "localhost:3000",
      "remoteAddress": "127.0.0.1",
      "remotePort": 63308
    }
    res: {
      "statusCode": 500
    }
    err: {
      "type": "TypeError",
      "message": "Cannot read property 'encrypted' of undefined",
      "stack":
          TypeError: Cannot read property 'encrypted' of undefined
              at Object.formatHttpRequest (/Users/trentm/el/ecs-logging-nodejs2/helpers/lib/http-formatters.js:49:26)
              at Object.<anonymous> (/Users/trentm/el/ecs-logging-nodejs2/helpers/fastify-example.js:6:11)
              at preHandlerCallback (/Users/trentm/el/ecs-logging-nodejs2/helpers/node_modules/fastify/lib/handleRequest.js:124:28)
              at preValidationCallback (/Users/trentm/el/ecs-logging-nodejs2/helpers/node_modules/fastify/lib/handleRequest.js:107:5)
              at handler (/Users/trentm/el/ecs-logging-nodejs2/helpers/node_modules/fastify/lib/handleRequest.js:70:7)
              at handleRequest (/Users/trentm/el/ecs-logging-nodejs2/helpers/node_modules/fastify/lib/handleRequest.js:18:5)
              at runPreParsing (/Users/trentm/el/ecs-logging-nodejs2/helpers/node_modules/fastify/lib/route.js:390:5)
              at Object.routeHandler [as handler] (/Users/trentm/el/ecs-logging-nodejs2/helpers/node_modules/fastify/lib/route.js:348:7)
              at Router.lookup (/Users/trentm/el/ecs-logging-nodejs2/helpers/node_modules/find-my-way/index.js:367:14)
              at Server.emit (events.js:314:20)
    }
[1612823104790] INFO (28873 on pink.local): request completed
    reqId: 1
    res: {
      "statusCode": 500
    }
    responseTime: 5.420830011367798
```

Thanks! Much nicer to know the particular issue.
