### ISSUE TITLE
Can't resolve 'elastic-apm-node' 

### ISSUE THREAD

**Issue by aniketbiprojit** [elastic/ecs-logging-nodejs#189]
⚠ ./node_modules/.pnpm/@elastic+ecs-winston-format@1.5.3/node_modules/@elastic/ecs-winston-format/index.js
Module not found: Can't resolve 'elastic-apm-node' in '.pnpm/@elastic+ecs-winston-format@1.5.3/node_modules/@elastic/ecs-winston-format'

Should I need to install this? I am not using elastic-apm-node anywhere.

This happens when I trying to integrate with Nextjs. Runs fine otherwise.

```ts
export const logger = winston.createLogger({
  format: ecsFormat(),
  transports: [
    new winston.transports.Console(),
    new winston.transports.File({ filename: `${outLogPath}/out-json.log` }),
  ],
});
```

This seems to be silently ignored in js file but I still get this error logged in NextJS logs.

Any ideas on how to suppress this error?

<img width="360" alt="image" src="https://github.com/elastic/ecs-logging-nodejs/assets/24915107/61bc169c-6942-4307-822a-036c7bb1c09e">

**Comment by trentm** [comment]
@aniketbiprojit Sorry about the delay in responding!

As you have found the usage of `elastic-apm-node` in the `@elastic/ecs-winston-format` module is meant to be silent if it cannot find that module.

You say you are using Next.js. That often means that a *bundler* is being used to produce a single .js file (or set of .js files) that are being run, instead of using the tree of files under `./node_modules/...`.  Do you know if that is the case for you?

Can you show the actual .js code that is doing that `elasticApm = require('elastic-apm-node')` call? Is it actually `./node_modules/.pnpm/https://github.com/elastic+ecs-winston-format@1.5.3/node_modules/@elastic/ecs-winston-format/index.js` or is that a source-map'ped point from a large bundle JS file?

Are you getting that `Module not found: Can't resolve 'elastic-apm-node'` at **build/compile time**? Or at runtime?
From your comment "but I still get this error logged in NextJS logs." ... I'm guessing this is at runtime.

If this *is* in a bundle, I'd love to see that bundle file. It may be that you cannot share the whole thing, if it has proprietary code in it, however.

**Comment by aniketbiprojit** [comment]
Hi. I kind of gave up on the package and wrote my own formatter for the same. 

So the error was at compile time (dev and build processes). Never reached runtime.

**Comment by aniketbiprojit** [comment]
Also when I installed `elastic-apm-node` it was throwing the same error for missing deps which are imported in `elastic-apm-node`.

**Comment by andrewstec** [comment]
Great library, but this is making a lot of noise. I am using webpack and pnp as well.

```
[1] WARNING in ./.yarn/cache/elastic-apm-node-npm-4.8.0-de2b5f486c-f3a4625d61.zip/node_modules/elastic-apm-node/lib/opentelemetry-bridge/opentelemetry-core-mini/trace/TraceState.js
[1] Module Warning (from ./.yarn/__virtual__/source-map-loader-virtual-f8b047c3d9/0/cache/source-map-loader-npm-5.0.0-62d48efeee-9bc90a50df.zip/node_modules/source-map-loader/dist/cjs.js):
[1] Failed to parse source map from '/Users/samspaghetti/repos/pasta/project/backend/.yarn/cache/elastic-apm-node-npm-4.8.0-de2b5f486c-f3a4625d61.zip/node_modules/elastic-apm-node/lib/opentelemetry-bridge/opentelemetry-core-mini/trace/TraceState.js.map' file: Error: ENOENT: no such file or directory, open '/node_modules/elastic-apm-node/lib/opentelemetry-bridge/opentelemetry-core-mini/trace/TraceState.js.map'
[1] Error: Failed to parse source map from '/Users/samspaghetti/repos/pasta/project/backend/.yarn/cache/elastic-apm-node-npm-4.8.0-de2b5f486c-f3a4625d61.zip/node_modules/elastic-apm-node/lib/opentelemetry-bridge/opentelemetry-core-mini/trace/TraceState.js.map' file: Error: ENOENT: no such file or directory, open '/node_modules/elastic-apm-node/lib/opentelemetry-bridge/opentelemetry-core-mini/trace/TraceState.js.map'
[1]     at fetchFromFilesystem (/Users/samspaghetti/repos/pasta/project/backend/.yarn/__virtual__/source-map-loader-virtual-f8b047c3d9/0/cache/source-map-loader-npm-5.0.0-62d48efeee-9bc90a50df.zip/node_modules/source-map-loader/dist/utils.js:115:11)
[1]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[1]     at async fetchFromURL (/Users/samspaghetti/repos/pasta/project/backend/.yarn/__virtual__/source-map-loader-virtual-f8b047c3d9/0/cache/source-map-loader-npm-5.0.0-62d48efeee-9bc90a50df.zip/node_modules/source-map-loader/dist/utils.js:208:9)
[1]     at async Object.loader (/Users/samspaghetti/repos/pasta/project/backend/.yarn/__virtual__/source-map-loader-virtual-f8b047c3d9/0/cache/source-map-loader-npm-5.0.0-62d48efeee-9bc90a50df.zip/node_modules/source-map-loader/dist/index.js:51:9)
[1]  @ ./.yarn/cache/elastic-apm-node-npm-4.8.0-de2b5f486c-f3a4625d61.zip/node_modules/elastic-apm-node/lib/opentelemetry-bridge/otelutils.js 15:23-76
[1]  @ ./.yarn/cache/elastic-apm-node-npm-4.8.0-de2b5f486c-f3a4625d61.zip/node_modules/elastic-apm-node/lib/opentelemetry-bridge/OTelBridgeNonRecordingSpan.js 13:46-68
[1]  @ ./.yarn/cache/elastic-apm-node-npm-4.8.0-de2b5f486c-f3a4625d61.zip/node_modules/elastic-apm-node/lib/opentelemetry-bridge/OTelBridgeRunContext.js 12:39-78
[1]  @ ./.yarn/cache/elastic-apm-node-npm-4.8.0-de2b5f486c-f3a4625d61.zip/node_modules/elastic-apm-node/lib/opentelemetry-bridge/index.js 9:33-66
[1]  @ ./.yarn/cache/elastic-apm-node-npm-4.8.0-de2b5f486c-f3a4625d61.zip/node_modules/elastic-apm-node/lib/agent.js 351:8-41
[1]  @ ./.yarn/cache/elastic-apm-node-npm-4.8.0-de2b5f486c-f3a4625d61.zip/node_modules/elastic-apm-node/index.js 9:12-34
[1]  @ ./.yarn/cache/@elastic-ecs-winston-format-npm-1.5.3-67d8db26d9-19efeefe8b.zip/node_modules/@elastic/ecs-winston-format/index.js 33:15-42
[1]  @ ./src/core/utils/logger.ts 19:29-67
[1]  @ ./src/core/middleware/loggingMiddleware.ts 4:17-43
[1]  @ ./src/core/server.ts 8:28-69
[1]  @ ./src/server.ts 7:33-57
[1] 
```

This was taken from the bundle .js file:

```
/**
 * Tries to load a configuration file for the given path or from the ENV vars, if both undefined
 * it uses the default config filename `elastic-apm-node.js`. If the config file is not present or
 * there is something wrong in the file it will return no options
 * @param {string} [confPath] the path to the file
 * @returns {Record<string,any> | null}
 */
function readFileOptions(confPath) {
  const configFileDef = CONFIG_SCHEMA.find((def) => def.name === 'configFile');
  const defaultValue = configFileDef.defaultValue;
  const envValue = process.env[configFileDef.envVar];
  const filePath = path.resolve(confPath || envValue || defaultValue);

  if (fs.existsSync(filePath)) {
    try {
      return __webpack_require__(407)(filePath);
    } catch (err) {
      console.error(
        "Elastic APM initialization error: Can't read config file %s",
        filePath,
      );
      console.error(err.stack);
    }
  }

  return null;
}
```

I don't think this is an initialization error. I don't see that error. I don't see this being required. I searched from 'require('elastic'. No matches. I do see this:

```
"use strict";
module.exports = /*#__PURE__*/JSON.parse('{"name":"elastic-apm-node","version":"4.8.0","description":"The official Elastic APM agent for Node.js","type":"commonjs","main":"index.js","types":"index.d.ts","scripts":{"docs:open":"PREVIEW=1 npm run docs:build","docs:build":"./docs/scripts/build_docs.sh apm-agent-nodejs ./docs ./build","lint":"npm run lint:eslint && npm run lint:license-files && npm run lint:yaml-files && npm run lint:tav","lint:eslint":"eslint . # r
```

Hopefully this info helps. I'm thinking of gutting this library and writing my own too, although I'd rather use this if this could be fixed.

**Comment by KoenBrouwer** [comment]
I just decided to patch this part of the dependency (using `pnpm patch`) to not have it require `elastic-apm-node`. It now shuts up and the actual logger still works fine (with APM disabled).

```diff
      // `require('@elastic/ecs-pino-format')` and has a "node_modules/"
      // where 'elastic-apm-node' shares the same ecs-pino-format install.
      try {
-        elasticApm = require('elastic-apm-node')
+        // Patched: This is commented out to avoid a runtime dependency on elastic-apm-node, which we don't use.
+        // elasticApm = require('elastic-apm-node')
      } catch (ex) {
        // Silently ignore.
      }
```

**Comment by aniketbiprojit** [comment]
@KoenBrouwer Pretty much did the same. I copied out the file to local, disabled eslint for the file and then imported it.

**Comment by chris-hmmr** [comment]
I encountered the same issue today for my next.js environment and patched it, similar as @KoenBrouwer did.

**Comment by ammarisrar** [comment]
Having the same issue - I suggest an APM-free version with this chunk removed, as a separate version.
