### ISSUE TITLE
Logging an object that contains 'response' key crashes things.

### ISSUE THREAD

**Issue by boneill42** [elastic/ecs-logging-nodejs#59]
If you have a "response" field in the object that you are logging, you end up wtih:

```
(node:83383) UnhandledPromiseRejectionWarning: TypeError: res.getHeaders is not a function
    at formatHttpResponse (/Users/bone/git/snapyr-io-plane/src/processes/http/node_modules/@elastic/ecs-helpers/http-formatters.js:84:21)
    at Format.ecsFormat (/Users/bone/git/snapyr-io-plane/src/processes/http/node_modules/@elastic/ecs-winston-format/index.js:42:5)
    at DerivedLogger._transform (/Users/bone/git/snapyr-io-plane/node_modules/winston/lib/winston/logger.js:305:29)
    at DerivedLogger.Transform._read (/Users/bone/git/snapyr-io-plane/node_modules/readable-stream/lib/_stream_transform.js:177:10)
    at DerivedLogger.Transform._write (/Users/bone/git/snapyr-io-plane/node_modules/readable-stream/lib/_stream_transform.js:164:83)
    at doWrite (/Users/bone/git/snapyr-io-plane/node_modules/readable-stream/lib/_stream_writable.js:409:139)
    at writeOrBuffer (/Users/bone/git/snapyr-io-plane/node_modules/readable-stream/lib/_stream_writable.js:398:5)
    at DerivedLogger.Writable.write (/Users/bone/git/snapyr-io-plane/node_modules/readable-stream/lib/_stream_writable.js:307:11)
    at DerivedLogger.log (/Users/bone/git/snapyr-io-plane/node_modules/winston/lib/winston/logger.js:244:14)
    at DerivedLogger.<computed> [as debug] (/Users/bone/git/snapyr-io-plane/node_modules/winston/lib/winston/create-logger.js:95:19)
(Use `node --trace-warnings ...` to show where the warning was created)
```

Because the code expects that to be a Response.  (even when its not)

There should be better error handling and warnings if response is a key, but is not a response object.

**Comment by trentm** [comment]
@boneill42 Thanks. I will take a look (at this and the ticket you opened yesterday) soon.

**Comment by trentm** [comment]
From the line numbers, it looks to me like you are using a pre-1.0.0 version of `@elastic/ecs-winston-format`. Since then the "response" field is no longer handled: just the "res" field. However, the similar issue still exists with the "res" key with the latest version of the package:

```
% npm ls @elastic/ecs-winston-format
p3@1.0.0 /Users/trentm/tmp/p3
└── @elastic/ecs-winston-format@1.0.0

% cat foo.js
const winston = require('winston')
const ecsFormat = require('@elastic/ecs-winston-format')
const logger = winston.createLogger({
  format: ecsFormat({ convertReqRes: true }),
  transports: [
    new winston.transports.Console()
  ]
})

logger.info('response in fields', { response: 'hi' })
logger.info('res in fields', { res: 'hi' })

% node foo.js
{"@timestamp":"2021-03-18T19:05:10.826Z","log.level":"info","message":"response in fields","ecs":{"version":"1.6.0"},"response":"hi"}
/Users/trentm/tmp/p3/node_modules/winston/lib/winston/logger.js:307
      throw ex;
      ^

TypeError: res.getHeaders is not a function
    at formatHttpResponse (/Users/trentm/tmp/p3/node_modules/@elastic/ecs-helpers/lib/http-formatters.js:120:23)
    at Format.ecsTransform [as transform] (/Users/trentm/tmp/p3/node_modules/@elastic/ecs-winston-format/index.js:142:7)
    at DerivedLogger._transform (/Users/trentm/tmp/p3/node_modules/winston/lib/winston/logger.js:305:29)
    at DerivedLogger.Transform._read (/Users/trentm/tmp/p3/node_modules/readable-stream/lib/_stream_transform.js:177:10)
    at DerivedLogger.Transform._write (/Users/trentm/tmp/p3/node_modules/readable-stream/lib/_stream_transform.js:164:83)
    at doWrite (/Users/trentm/tmp/p3/node_modules/readable-stream/lib/_stream_writable.js:409:139)
    at writeOrBuffer (/Users/trentm/tmp/p3/node_modules/readable-stream/lib/_stream_writable.js:398:5)
    at DerivedLogger.Writable.write (/Users/trentm/tmp/p3/node_modules/readable-stream/lib/_stream_writable.js:307:11)
    at DerivedLogger.log (/Users/trentm/tmp/p3/node_modules/winston/lib/winston/logger.js:244:14)
    at DerivedLogger.(anonymous function) [as info] (/Users/trentm/tmp/p3/node_modules/winston/lib/winston/create-logger.js:95:19)
```

`formatHttpResponse` is not nearly defensive enough.

**Comment by trentm** [comment]
A version v1.1.0 has been published with this fix. Thanks for the issue!
