### ISSUE TITLE
Exception when logging response headers

### ISSUE THREAD

**Issue by orgads** [elastic/ecs-logging-nodejs#86]
Hi,

I'm trying to log the response headers, but an exception is raised by ecs formatter. This is my code:

```javascript
const winston = require('winston');
const express = require('express');
const ecsFormat = require('@elastic/ecs-winston-format');

const app = express();
app.use(express.json());

const logger = winston.createLogger({
    format: ecsFormat(),
    transports: [
        new winston.transports.Console()
    ]
});

app.get('/', (req, res) => {
  logger.info(res.getHeaders());
  res.end();
});

app.listen(5000);
```

This is the exception:
```
TypeError: str.toString is not a function
at $asString (eval at build (F:\Projects\jstest\node_modules\fast-json-stringify\index.js:147:20), <anonymous>:106:15)
    at $main (eval at build (F:\Projects\jstest\node_modules\fast-json-stringify\index.js:147:20), <anonymous>:223:17)
    at Format.ecsTransform [as transform] (F:\Projects\jstest\node_modules\@elastic\ecs-winston-format\index.js:183:19)
    at DerivedLogger._transform (F:\Projects\jstest\node_modules\winston\lib\winston\logger.js:305:29)
    at DerivedLogger._read (F:\Projects\jstest\node_modules\readable-stream\lib\_stream_transform.js:177:10)
    at DerivedLogger._write (F:\Projects\jstest\node_modules\readable-stream\lib\_stream_transform.js:164:83)
    at doWrite (F:\Projects\jstest\node_modules\readable-stream\lib\_stream_writable.js:405:139)
    at writeOrBuffer (F:\Projects\jstest\node_modules\readable-stream\lib\_stream_writable.js:394:5)
    at DerivedLogger.write (F:\Projects\jstest\node_modules\readable-stream\lib\_stream_writable.js:303:11)
    at DerivedLogger.info (F:\Projects\jstest\node_modules\winston\lib\winston\create-logger.js:81:14)
    at <anonymous> (F:\Projects\jstest\test.ts:16)
```

The object returned by `getHeaders()` is not an `Object`. It has only the fields, without any prototype. So calling `toString()` on it raises this exception.

`JSON.stringify` works on this object just fine.

A possible workaround is to pass `{...res.getHeaders()}`.

**Comment by trentm** [comment]
@orgads  Thank you very much for this report. I am very sorry that I did not to a crash report back when you originally opened this.

I can repro this against v1.4.0 (the current latest release):

```
% (sleep 1 && curl -i localhost:5000/)& ; node repro86.js
[1] 12443
HTTP/1.1 500 Internal Server Error
X-Powered-By: Express
Content-Security-Policy: default-src 'none'
X-Content-Type-Options: nosniff
Content-Type: text/html; charset=utf-8
Content-Length: 1753
Date: Fri, 27 Oct 2023 23:04:33 GMT
Connection: keep-alive
Keep-Alive: timeout=5

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>TypeError: str.toString is not a function<br> &nbsp; &nbsp;at $asString (eval at build (/Users/trentm/tmp/ecs-logging-nodejs/loggers/winston/node_modules/fast-json-stringify/index.js:155:20), &lt;anonymous&gt;:103:15)<br> &nbsp; &nbsp;at $main (eval at build (/Users/trentm/tmp/ecs-logging-nodejs/loggers/winston/node_modules/fast-json-stringify/index.js:155:20), &lt;anonymous&gt;:218:17)<br> &nbsp; &nbsp;at Format.ecsTransform [as transform] (/Users/trentm/tmp/ecs-logging-nodejs/loggers/winston/index.js:176:19)<br> &nbsp; &nbsp;at DerivedLogger._transform (/Users/trentm/tmp/ecs-logging-nodejs/loggers/winston/node_modules/winston/lib/winston/logger.js:313:29)<br> &nbsp; &nbsp;at DerivedLogger.Transform._read (/Users/trentm/tmp/ecs-logging-nodejs/loggers/winston/node_modules/readable-stream/lib/_stream_transform.js:166:10)<br> &nbsp; &nbsp;at DerivedLogger.Transform._write (/Users/trentm/tmp/ecs-logging-nodejs/loggers/winston/node_modules/readable-stream/lib/_stream_transform.js:155:83)<br> &nbsp; &nbsp;at doWrite (/Users/trentm/tmp/ecs-logging-nodejs/loggers/winston/node_modules/readable-stream/lib/_stream_writable.js:390:139)<br> &nbsp; &nbsp;at writeOrBuffer (/Users/trentm/tmp/ecs-logging-nodejs/loggers/winston/node_modules/readable-stream/lib/_stream_writable.js:381:5)<br> &nbsp; &nbsp;at DerivedLogger.Writable.write (/Users/trentm/tmp/ecs-logging-nodejs/loggers/winston/node_modules/readable-stream/lib/_stream_writable.js:302:11)<br> &nbsp; &nbsp;at DerivedLogger.&lt;computed&gt; [as info] (/Users/trentm/tmp/ecs-logging-nodejs/loggers/winston/node_modules/winston/lib/winston/create-logger.js:81:14)</pre>
</body>
</html>
[1]  + done       ( sleep 1 && curl -i localhost:5000/; )
TypeError: str.toString is not a function
    at $asString (eval at build (/Users/trentm/tmp/ecs-logging-nodejs/loggers/winston/node_modules/fast-json-stringify/index.js:155:20), <anonymous>:103:15)
    at $main (eval at build (/Users/trentm/tmp/ecs-logging-nodejs/loggers/winston/node_modules/fast-json-stringify/index.js:155:20), <anonymous>:218:17)
    at Format.ecsTransform [as transform] (/Users/trentm/tmp/ecs-logging-nodejs/loggers/winston/index.js:176:19)
    at DerivedLogger._transform (/Users/trentm/tmp/ecs-logging-nodejs/loggers/winston/node_modules/winston/lib/winston/logger.js:313:29)
    at DerivedLogger.Transform._read (/Users/trentm/tmp/ecs-logging-nodejs/loggers/winston/node_modules/readable-stream/lib/_stream_transform.js:166:10)
    at DerivedLogger.Transform._write (/Users/trentm/tmp/ecs-logging-nodejs/loggers/winston/node_modules/readable-stream/lib/_stream_transform.js:155:83)
    at doWrite (/Users/trentm/tmp/ecs-logging-nodejs/loggers/winston/node_modules/readable-stream/lib/_stream_writable.js:390:139)
    at writeOrBuffer (/Users/trentm/tmp/ecs-logging-nodejs/loggers/winston/node_modules/readable-stream/lib/_stream_writable.js:381:5)
    at DerivedLogger.Writable.write (/Users/trentm/tmp/ecs-logging-nodejs/loggers/winston/node_modules/readable-stream/lib/_stream_writable.js:302:11)
    at DerivedLogger.<computed> [as info] (/Users/trentm/tmp/ecs-logging-nodejs/loggers/winston/node_modules/winston/lib/winston/create-logger.js:81:14)
^C
```


However, I can **not** reproduce it with the latest commit in main:

```
% (sleep 1 && curl -i localhost:5000/)& ; node repro86.js
[1] 15093
{"@timestamp":"2023-10-27T23:07:36.534Z","ecs.version":"8.10.0","log.level":"info","message":{"x-powered-by":"Express"}}
HTTP/1.1 200 OK
X-Powered-By: Express
Date: Fri, 27 Oct 2023 23:07:36 GMT
Connection: keep-alive
Keep-Alive: timeout=5
Content-Length: 0

[1]  + done       ( sleep 1 && curl -i localhost:5000/; )
^C
```


The failure above is in `fast-json-stringify` dependency that *was* being used for JSON serialization. In #155 we recently changed to using `safe-stable-stringify` instead and I believe that has resolved this issue. I hope to have a release out early next week with this fix.

**Comment by trentm** [comment]
@orgads  Thank you very much for this report. I am very sorry that I did not to a crash report back when you originally opened this.

I can repro this against v1.4.0 (the current latest release):

```
% (sleep 1 && curl -i localhost:5000/)& ; node repro86.js
[1] 12443
HTTP/1.1 500 Internal Server Error
X-Powered-By: Express
Content-Security-Policy: default-src 'none'
X-Content-Type-Options: nosniff
Content-Type: text/html; charset=utf-8
Content-Length: 1753
Date: Fri, 27 Oct 2023 23:04:33 GMT
Connection: keep-alive
Keep-Alive: timeout=5

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>TypeError: str.toString is not a function<br> &nbsp; &nbsp;at $asString (eval at build (/Users/trentm/tmp/ecs-logging-nodejs/loggers/winston/node_modules/fast-json-stringify/index.js:155:20), &lt;anonymous&gt;:103:15)<br> &nbsp; &nbsp;at $main (eval at build (/Users/trentm/tmp/ecs-logging-nodejs/loggers/winston/node_modules/fast-json-stringify/index.js:155:20), &lt;anonymous&gt;:218:17)<br> &nbsp; &nbsp;at Format.ecsTransform [as transform] (/Users/trentm/tmp/ecs-logging-nodejs/loggers/winston/index.js:176:19)<br> &nbsp; &nbsp;at DerivedLogger._transform (/Users/trentm/tmp/ecs-logging-nodejs/loggers/winston/node_modules/winston/lib/winston/logger.js:313:29)<br> &nbsp; &nbsp;at DerivedLogger.Transform._read (/Users/trentm/tmp/ecs-logging-nodejs/loggers/winston/node_modules/readable-stream/lib/_stream_transform.js:166:10)<br> &nbsp; &nbsp;at DerivedLogger.Transform._write (/Users/trentm/tmp/ecs-logging-nodejs/loggers/winston/node_modules/readable-stream/lib/_stream_transform.js:155:83)<br> &nbsp; &nbsp;at doWrite (/Users/trentm/tmp/ecs-logging-nodejs/loggers/winston/node_modules/readable-stream/lib/_stream_writable.js:390:139)<br> &nbsp; &nbsp;at writeOrBuffer (/Users/trentm/tmp/ecs-logging-nodejs/loggers/winston/node_modules/readable-stream/lib/_stream_writable.js:381:5)<br> &nbsp; &nbsp;at DerivedLogger.Writable.write (/Users/trentm/tmp/ecs-logging-nodejs/loggers/winston/node_modules/readable-stream/lib/_stream_writable.js:302:11)<br> &nbsp; &nbsp;at DerivedLogger.&lt;computed&gt; [as info] (/Users/trentm/tmp/ecs-logging-nodejs/loggers/winston/node_modules/winston/lib/winston/create-logger.js:81:14)</pre>
</body>
</html>
[1]  + done       ( sleep 1 && curl -i localhost:5000/; )
TypeError: str.toString is not a function
    at $asString (eval at build (/Users/trentm/tmp/ecs-logging-nodejs/loggers/winston/node_modules/fast-json-stringify/index.js:155:20), <anonymous>:103:15)
    at $main (eval at build (/Users/trentm/tmp/ecs-logging-nodejs/loggers/winston/node_modules/fast-json-stringify/index.js:155:20), <anonymous>:218:17)
    at Format.ecsTransform [as transform] (/Users/trentm/tmp/ecs-logging-nodejs/loggers/winston/index.js:176:19)
    at DerivedLogger._transform (/Users/trentm/tmp/ecs-logging-nodejs/loggers/winston/node_modules/winston/lib/winston/logger.js:313:29)
    at DerivedLogger.Transform._read (/Users/trentm/tmp/ecs-logging-nodejs/loggers/winston/node_modules/readable-stream/lib/_stream_transform.js:166:10)
    at DerivedLogger.Transform._write (/Users/trentm/tmp/ecs-logging-nodejs/loggers/winston/node_modules/readable-stream/lib/_stream_transform.js:155:83)
    at doWrite (/Users/trentm/tmp/ecs-logging-nodejs/loggers/winston/node_modules/readable-stream/lib/_stream_writable.js:390:139)
    at writeOrBuffer (/Users/trentm/tmp/ecs-logging-nodejs/loggers/winston/node_modules/readable-stream/lib/_stream_writable.js:381:5)
    at DerivedLogger.Writable.write (/Users/trentm/tmp/ecs-logging-nodejs/loggers/winston/node_modules/readable-stream/lib/_stream_writable.js:302:11)
    at DerivedLogger.<computed> [as info] (/Users/trentm/tmp/ecs-logging-nodejs/loggers/winston/node_modules/winston/lib/winston/create-logger.js:81:14)
^C
```


However, I can **not** reproduce it with the latest commit in main:

```
% (sleep 1 && curl -i localhost:5000/)& ; node repro86.js
[1] 15093
{"@timestamp":"2023-10-27T23:07:36.534Z","ecs.version":"8.10.0","log.level":"info","message":{"x-powered-by":"Express"}}
HTTP/1.1 200 OK
X-Powered-By: Express
Date: Fri, 27 Oct 2023 23:07:36 GMT
Connection: keep-alive
Keep-Alive: timeout=5
Content-Length: 0

[1]  + done       ( sleep 1 && curl -i localhost:5000/; )
^C
```


The failure above is in `fast-json-stringify` dependency that *was* being used for JSON serialization. In #155 we recently changed to using `safe-stable-stringify` instead and I believe that has resolved this issue. I hope to have a release out early next week with this fix.

**Comment by orgads** [comment]
Thank you.
